// data.js - 全国行脚の中身（観光地リスト）
// このファイルに観光地を書き足すだけで、ランダムに出てくる候補が増えます。

// サイト全体の設定
const ANGYA_CONFIG = {
    title: 'リサゆき全国行脚',
    description: 'ボタンを押すと、友希那とリサが日本のどこかへ飛ばされます。その様子を観察してみましょう。',
};

// 観光地一覧
// name: 名前 / pref: 都道府県 / city: 市町村 / region: 地方
// description: 紹介文 / tags: キーワード（なくてもOK）
// ss: 短編小説（なくてもOK。空欄なら表示されません）
//     ※ss だけは ` `（バッククォート）で囲むので、そのまま Enter で改行すると
//       サイト上でも同じ位置で改行されます。空行を入れれば段落も空けられます。
const SPOTS = [
    {
        name: 'ノーザンホースパーク',
        pref: '北海道',
        city: '苫小牧市',
        region: '北海道',
        description: '数々の名馬や乗用馬が暮らしている、馬と近づけるテーマパーク。馬車にも乗ることができる。',
        tags: ['自然', '動物'],
        ss: ``,
    },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
//     {
//         name: '',
//         pref: '',
//         city: '',
//         region: '',
//         description: '',
//         tags: ['', '', ''],
//         ss: ``,
//     },
];
